# -*- mode: ruby -*-
# vi: set ft=ruby :
# Vagrantfile - VMs Docker Swarm (3 noeuds)
# Projet DevOps - HAMMOUDI Anis, CHEDAD Mehdi, ZOUINE Sanaa

MANAGER_IP = "192.168.56.10"
WORKER1_IP = "192.168.56.11"  
WORKER2_IP = "192.168.56.12"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_check_update = false

  # Configuration VirtualBox commune
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 4096
    vb.cpus = 6
    vb.linked_clone = true
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  # Configuration SSH commune pour Ansible
  config.ssh.insert_key = false

  # Manager Node
  config.vm.define "manager" do |m|
    m.vm.hostname = "manager"
    m.vm.network "private_network", ip: MANAGER_IP
  end

  # Worker 1
  config.vm.define "worker1" do |w|
    w.vm.hostname = "worker1"
    w.vm.network "private_network", ip: WORKER1_IP
  end

  # Worker 2
  config.vm.define "worker2" do |w|
    w.vm.hostname = "worker2"
    w.vm.network "private_network", ip: WORKER2_IP
  end
end
